name: Set secret to .env

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        env:
          VUE_APP_GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
        run: yarn build