name: Deploy Vue.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# Adicionada essa linha para forçar o runner a usar a versão correta exigida pelo GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Atualizado para o Node 24
          cache: 'yarn'

      - name: Instalar Dependências
        run: yarn install

      - name: Build do Projeto
        run: yarn build

      - name: Configurar Páginas do GitHub
        uses: actions/configure-pages@v4

      - name: Upload do Artefato (pasta dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4